# .github/workflows/java.yml
name: Java Hello World Workflow
 
on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch
 
jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checkout your repository code
 
    - name: Set up JDK
      uses: actions/setup-java@v3  # Set up Java
      with:
        java-version: '17'  # Specify the Java version you want (e.g., 8, 11, 17)
        distribution: 'temurin'  # Use AdoptOpenJDK (or other distros like temurin)
 
    - name: Verify Java installation
      run: |
        java -version  # Print the installed Java version
        javac -version  # Print the installed Java compiler version
 
    - name: Compile Java code
      run: javac helloworld.java  # Compile the HelloWorld.java file
 
    - name: Run Java code
      run: java helloworld  # Run the compiled Java program

      
      - name: Print secret key for debugging (only temporarily)
      run: echo "The secret key is ${{ secrets.shruti0909 }}"  # Access and print the secret key (for debugging purposes)
      env:
        MY_SECRET_KEY: ${{ secrets.shruti0909 }}
    
